version: '2'

services:
    database:
        image: mariadb
        container_name: zmdb
        environment:
            - MYSQL_DATABASE=zoneminder
            - MYSQL_USER=zoneminder
            - MYSQL_PASSWORD=VozHfizmy9TBQ4WVyvuBChklicRyiuch2JxjzExN
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - ./data/mysql:/var/lib/mysql

    zoneminder:
        build: zm-base
        depends_on:
            - database
        env_file:
            - ./zoneminder.env
        volumes:
            - ./config/zoneminder:/config
        links:
            - database:zm.db

    frontend:
        image: nginx:stable-alpine
        depends_on:
            - zoneminder
        links:
            - zoneminder:zoneminder
        ports:
            - 80:80
            - 443:443

