version: '2'

services:
  database:
    image: mariadb
    container_name: zmdb
    env_file:
      - database.env
    volumes:
      - ./data/mysql:/var/lib/mysql

  zoneminder:
    build: zm-base
    depends_on:
      - database
    env_file:
      - ./zoneminder.env
    volumes:
      - ./config/zoneminder:/config
      - ./log:/var/log/zoneminder      
    links:
      - database:zm.db
  
  phpfpm:
    build: zm-fpm
    depends_on:
      - database
      - zoneminder
    env_file:
      - ./zoneminder.env
    links:
      - database:zm.db
      - zoneminder:zm

  frontend:
    build: zm-http
    depends_on:
      - database
      - zoneminder
    env_file:
      - ./zoneminder.env
    volumes:
      - ./vlz:/var/lib/zoneminder
      - ./log/apache:/var/log/apache
    links:
      - database:zm.db
      - zoneminder:zm
      - phpfpm:zm.phpfpm
    ports:
      - 80:80
      - 443:443

#    frontend:
#        image: nginx:stable-alpine
#        depends_on:
#            - zoneminder
#        links:
#            - zoneminder:zoneminder

